worker_processes auto;

events {
    worker_connections 4096;
}

stream {
    resolver 8.8.8.8 1.1.1.1 ipv6=off valid=300s;

    # Защита от пустых SNI (если обратились по IP, сбрасываем коннект на 127.0.0.1)
    map $ssl_preread_server_name $target_backend {
        default   $ssl_preread_server_name:443;
        ""        127.0.0.1:65535; # Несуществующий порт (сброс соединения)
    }

    server {
        # СЛУШАЕМ ТОЛЬКО ВНУТРЕННИЙ IP VPN! (Защита от Open Proxy)
        listen 10.8.0.1:443;

        ssl_preread on;

        # Очистка мертвых соединений
        proxy_connect_timeout 5s;
        proxy_timeout 60s;

        proxy_pass $target_backend;
    }
}

http {
    resolver 8.8.8.8 1.1.1.1 ipv6=off valid=300s;

    server {
        # СЛУШАЕМ ТОЛЬКО ВНУТРЕННИЙ IP VPN!
        listen 10.8.0.1:80;

        # Если нет заголовка Host, отдаем ошибку 400 (Bad Request)
        if ($http_host = "") {
            return 400;
        }

        location / {
            # Таймауты для HTTP-прокси
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            # Для проксирования лучше использовать $host вместо $http_host в URI
            # так как $http_host может содержать нестандартный порт
            proxy_pass http://$host$request_uri;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
