worker_processes auto;

events {
    worker_connections 2048;
}

stream {
    resolver 8.8.8.8 1.1.1.1 ipv6=off valid=300s;

    server {
        listen 443;
        
        ssl_preread on;
        
        proxy_pass $ssl_preread_server_name:443;
    }
}

http {
    resolver 8.8.8.8 1.1.1.1 ipv6=off;
    
    server {
        listen 80;
        
        location / {
            proxy_pass http://$http_host$request_uri;
            proxy_set_header Host $http_host;
        }
    }
}
